import { AprDocument, Prompt, Section } from "./model.js";
import { isSupportedVersion } from "./serialization.js";
import { inspectText } from "./unicode-security.js";
export interface ValidationIssue { code: string; message: string; path: string; }
export interface ValidationResult { errors: ValidationIssue[]; warnings: ValidationIssue[]; isValid: boolean; }

export function validate(document: AprDocument): ValidationResult {
  const errors: ValidationIssue[] = []; const warnings: ValidationIssue[] = [];
  const required = (value: string | undefined, path: string, label: string) => { if (!value?.trim()) errors.push({ code: "REQUIRED_FIELD", message: `${label} is required.`, path }); };
  required(document.version, "version", "version"); if (document.version && !isSupportedVersion(document.version)) errors.push({ code: "UNSUPPORTED_VERSION", message: `Unsupported APR version ${document.version}.`, path: "version" });
  required(document.metadata.title, "metadata.title", "metadata.title"); if (!document.sections.length) errors.push({ code: "REQUIRED_FIELD", message: "A document must have at least one section.", path: "sections" });
  if (document.documentType === "filledForm") required(document.metadata.templateId, "metadata.templateId", "A filled form templateId");
  const sectionIds: string[] = []; const promptIds: string[] = [];
  const walk = (section: Section, path: string): void => { const here = `${path}[${section.id || "?"}]`; required(section.id, here, "Section id"); required(section.title, `${here}.title`, "Section title"); sectionIds.push(section.id); if (!section.prompts.length && !section.sections.length && section.kind !== "table") errors.push({ code: "EMPTY_SECTION", message: "A section must contain prompts or child sections.", path: here }); for (const prompt of section.prompts) { const promptPath = `${here}.${prompt.id || "?"}`; required(prompt.id, promptPath, "Prompt id"); required(prompt.label, `${promptPath}.label`, "Prompt label"); promptIds.push(prompt.id); warnings.push(...advisoriesFor(prompt)); } for (const child of section.sections) walk(child, here); };
  for (const section of document.sections) walk(section, "sections");
  for (const [kind, ids] of [["section", sectionIds], ["prompt", promptIds]] as const) { const seen = new Set<string>(); for (const id of ids) { if (id && seen.has(id)) errors.push({ code: "DUPLICATE_ID", message: `Duplicate ${kind} id: ${id}`, path: id }); seen.add(id); } }
  return { errors, warnings, isValid: errors.length === 0 };
}
export function advisoriesFor(prompt: Prompt): ValidationIssue[] { const warnings: ValidationIssue[] = inspectText(prompt.response).map(finding => ({ code: finding.code, message: `Response contains a hidden or visually deceptive character (${finding.description}) at offset ${finding.offset}. It was preserved; verify it was intentional.`, path: prompt.id })); if (!prompt.response) return warnings; const hints = prompt.hints; if (hints.validationPattern) { try { if (!new RegExp(hints.validationPattern).test(prompt.response)) return [...warnings, { code: "PATTERN_MISMATCH", message: "Response does not match the suggested pattern.", path: prompt.id }]; } catch { return [...warnings, { code: "PATTERN_MISMATCH", message: "The suggested pattern is not a valid regex.", path: prompt.id }]; } } const looks = (type: string, value: string): boolean => ({ email: /@.+\./.test(value), number: Number.isFinite(Number(value)), range: Number.isFinite(Number(value)), currency: Number.isFinite(Number(value.replace(/[^0-9.eE+-]/g, ""))), date: /^\d{4}-\d\d-\d\d/.test(value), url: /^https?:\/\//.test(value), boolean: /^(true|false|yes|no|1|0)$/i.test(value) }[type] ?? true); if (hints.expectedDataType && !looks(hints.expectedDataType, prompt.response)) warnings.push({ code: "TYPE_MISMATCH", message: `Response does not look like ${hints.expectedDataType} (advisory).`, path: prompt.id }); if (hints.suggestedValues.length && !hints.suggestedValues.includes(prompt.response)) warnings.push({ code: "OUTSIDE_SUGGESTED", message: "Response is outside the suggested options.", path: prompt.id }); return warnings; }
