using System.Globalization;
using System.Text;
using System.Text.Json;
using AwesomeAssertions;
using Xunit;

namespace PromptResponse.Rendering.Pdf.Tests;

/// <summary>
/// Runs every measurement that exists today over every corpus form, and commits
/// the numbers so they can be diffed.
/// </summary>
/// <remarks>
/// <para>
/// Only one conversion path exists: the AcroForm importer. The text-layer
/// converter, vector geometry, label recovery and the model verifier are not
/// built, so this scores step 0 and nothing else. That is the honest baseline,
/// and writing it down now is what makes "has this got better" answerable later
/// — before this, there was no per-form number to compare against at all.
/// </para>
/// <para>
/// The scorecard is committed rather than printed. A number that vanishes when
/// the test run ends cannot show a trend, and a trend is the whole point.
/// </para>
/// </remarks>
public class PipelineScorecardTests
{
    private static readonly string[] Forms =
    [
        "fed-w9", "fed-w4", "fed-ss4", "fed-8822", "fed-i9",
        "ct-w4", "ct-dmv-j23", "ct-dmv-b58ind", "ct-dmv-a25", "ct-dmv-a83", "ct-dmv-b225p",
    ];

    [Fact]
    public void TheCommittedScorecardMatchesWhatThePipelineProducesNow()
    {
        // The committed file is LF on every platform (.gitattributes); the builder writes
        // the platform newline, which on Windows is CRLF.
        var report = BuildScorecard().ReplaceLineEndings("\n");
        var path = Path.Combine(RepoRoot, "scripts", "pdf-form-benchmark", "SCORECARD.md");

        if (Environment.GetEnvironmentVariable("UPDATE_SCORECARD") == "1")
        {
            File.WriteAllText(path, report);
            return;
        }

        File.Exists(path).Should().BeTrue("the scorecard is committed; regenerate with UPDATE_SCORECARD=1");
        File.ReadAllText(path).Should().Be(report,
            "a change here is a change in how the pipeline performs -- review it rather than absorb it");
    }

    [Fact]
    public void TheAcroFormPathLosesNoFieldOnAnyForm()
    {
        // The one end-to-end claim that can be made today, asserted per form
        // rather than left to the prose of a report.
        foreach (var id in Forms)
        {
            var manifest = PdfWidgetManifest.Extract(CorpusPath(id));
            var coverage = PdfWidgetManifest.Compare(manifest, new PdfFormImporter().Import(CorpusPath(id), id));

            coverage.IsComplete.Should().BeTrue(
                $"{id}: importer dropped {string.Join(", ", coverage.MissingFieldNames)}");
            coverage.UnaccountedPromptIds.Should().BeEmpty(
                $"{id}: importer invented {string.Join(", ", coverage.UnaccountedPromptIds)}");
        }
    }

    private static string BuildScorecard()
    {
        var rows = new List<Row>();
        foreach (var id in Forms)
        {
            var manifest = PdfWidgetManifest.Extract(CorpusPath(id));
            var (document, quality) = new PdfFormImporter().ImportWithQuality(CorpusPath(id), id);
            var reference = LoadReference(id);

            var coverage = PdfWidgetManifest.Compare(manifest, document);
            var geometric = PdfOrderAgreement.Compare(reference, document);
            var declared = PdfOrderAgreement.Compare(reference, document, useDeclarationOrder: true);

            rows.Add(new Row(
                id,
                reference.Fields.Count,
                coverage.Fraction,
                coverage.UnaccountedPromptIds.Count,
                quality.TooltipCoverage,
                quality.CrypticLabelRatio,
                quality.Score,
                quality.Grade,
                quality.Recommendation.ToString(),
                declared.Tau,
                geometric.Tau,
                reference.Lines.Count));
        }

        var sb = new StringBuilder();
        sb.AppendLine("# PDF-to-APR pipeline scorecard");
        sb.AppendLine();
        sb.AppendLine("Generated by `PipelineScorecardTests`; regenerate with `UPDATE_SCORECARD=1 dotnet test`.");
        sb.AppendLine("Committed so the numbers can be diffed — a scorecard that only ever prints cannot show a trend.");
        sb.AppendLine();
        sb.AppendLine("## What this does and does not cover");
        sb.AppendLine();
        sb.AppendLine("**Only the AcroForm importer exists.** The text-layer converter (#422), vector");
        sb.AppendLine("geometry (#424), label recovery (#426) and the model verifier (#423) are not built,");
        sb.AppendLine("so every number below describes step 0 on a form that already has form fields.");
        sb.AppendLine("Nothing here measures the converter's actual target case — a form with no AcroForm —");
        sb.AppendLine("because no code exists yet to convert one.");
        sb.AppendLine();
        sb.AppendLine("## Per form");
        sb.AppendLine();
        sb.AppendLine("| form | fields | coverage | invented | tooltips | cryptic | quality | grade | recommendation | tau(decl) | tau(geom) |");
        sb.AppendLine("| --- | ---: | ---: | ---: | ---: | ---: | ---: | :---: | --- | ---: | ---: |");
        foreach (var r in rows)
        {
            sb.AppendLine(string.Create(CultureInfo.InvariantCulture,
                $"| `{r.Id}` | {r.Fields} | {r.Coverage:P0} | {r.Invented} | {r.Tooltips:P0} | {r.Cryptic:P0} | {r.Score} | {r.Grade} | {r.Recommendation} | {r.TauDeclared:F3} | {r.TauGeometric:F3} |"));
        }

        sb.AppendLine();
        sb.AppendLine("## Totals");
        sb.AppendLine();
        sb.AppendLine(string.Create(CultureInfo.InvariantCulture,
            $"- **{rows.Sum(r => r.Fields)} fields** across {rows.Count} forms, **{rows.Sum(r => r.Lines)} lines** of reference text"));
        sb.AppendLine(string.Create(CultureInfo.InvariantCulture,
            $"- Field coverage: **{rows.Average(r => r.Coverage):P1}**, invented fields: **{rows.Sum(r => r.Invented)}**"));
        sb.AppendLine(string.Create(CultureInfo.InvariantCulture,
            $"- Tooltip coverage: **{rows.Sum(r => r.Tooltips * r.Fields) / rows.Sum(r => r.Fields):P0}** of fields carry the form author's own label"));
        sb.AppendLine(string.Create(CultureInfo.InvariantCulture,
            $"- Order vs geometric reading order: mean tau **{rows.Average(r => r.TauGeometric):F3}** (range {rows.Min(r => r.TauGeometric):F2}–{rows.Max(r => r.TauGeometric):F2})"));
        sb.AppendLine(string.Create(CultureInfo.InvariantCulture,
            $"- Forms an operator is told to use directly: **{rows.Count(r => r.Recommendation == "UseDirectly")}/{rows.Count}**"));
        sb.AppendLine();
        sb.AppendLine("## How to read these");
        sb.AppendLine();
        sb.AppendLine("- **coverage / invented** — against the PDF's own field list. Tier 1: the PDF states it.");
        sb.AppendLine("  100% is the floor for an AcroForm import, not an achievement; it means nothing was dropped.");
        sb.AppendLine("- **tau(decl)** — order against the AcroForm's declaration order. Usually 1.000, because");
        sb.AppendLine("  the importer emits fields as declared — but *not* tautologically so, and `fed-i9` proves it");
        sb.AppendLine("  at **0.276**. The importer groups prompts into one section per page (I-9: 51/38/39), and");
        sb.AppendLine("  I-9's AcroForm declares its fields interleaved across pages, giving 2,943 inversions.");
        sb.AppendLine("  Page grouping is the sensible behaviour; the number simply shows declaration order and");
        sb.AppendLine("  emitted order are not the same thing on every form.");
        sb.AppendLine("- **tau(geom)** — order against geometric reading order. The real signal, and the one a");
        sb.AppendLine("  flat-form converter will be graded on, since it has no access to declaration order.");
        sb.AppendLine("- **tooltips / cryptic** — how many labels are human-readable. This is the number the");
        sb.AppendLine("  converter is meant to improve, and it is why #426 exists.");
        sb.AppendLine("- **A present tooltip is not a good tooltip.** `ct-dmv-a25` reads 100% tooltips *and*");
        sb.AppendLine("  100% cryptic: every field carries a `/TU`, and every one of them says `TextField1`.");
        sb.AppendLine("  Tooltip coverage therefore overstates label quality, and #426's target population is");
        sb.AppendLine("  better defined by the cryptic ratio than by absent tooltips.");
        sb.AppendLine();
        return sb.ToString();
    }

    private sealed record Row(
        string Id, int Fields, double Coverage, int Invented, double Tooltips, double Cryptic,
        int Score, string Grade, string Recommendation, double TauDeclared, double TauGeometric, int Lines);

    private static PdfStructuredReference LoadReference(string id) =>
        JsonSerializer.Deserialize<PdfStructuredReference>(
            File.ReadAllText(Path.Combine(RepoRoot, "scripts", "pdf-form-benchmark", "reference", $"{id}.json")),
            PdfReferenceExtractor.JsonOptions)!;

    private static string CorpusPath(string id) =>
        Path.Combine(RepoRoot, "scripts", "pdf-form-benchmark", "corpus", $"{id}.pdf");

    private static string RepoRoot => Path.GetFullPath(
        Path.Combine(Directory.GetCurrentDirectory(), "..", "..", "..", "..", ".."));
}
