<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.1.1" />
    <PackageReference Include="Avalonia.Desktop" Version="12.1.1" />
    <PackageReference Include="coverlet.collector" Version="10.0.1" />
    <PackageReference Include="AwesomeAssertions" Version="9.6.0" />
    <PackageReference Include="Tmds.DBus" Version="0.95.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.9.0" />
    <PackageReference Include="xunit.v3.mtp-off" Version="3.2.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\PromptResponse.Core\PromptResponse.Core.csproj" />
    <ProjectReference Include="..\..\src\PromptResponse.Desktop\PromptResponse.Desktop.csproj" />
  </ItemGroup>

</Project>
