#!/usr/bin/env python3
"""Build the APR specification release manifest.

A release has to identify the exact set of artifacts it published, or "APR
1.0-beta.6" names a moving target. This records the specification and every
artifact derived from it, each with its SHA-256, so a tag identifies bytes rather
than a version string.

    python3 scripts/build-spec.py            # verify, exit non-zero on drift
    python3 scripts/build-spec.py --write    # regenerate the manifest

The manifest is checked in and verified in CI, so it cannot fall behind the
artifacts it claims to describe.

There is deliberately no rendered HTML or PDF here. The canonical source is
Markdown, it is readable as-is on any platform and in any editor, and a
generated rendering would be one more artifact to keep in step for no gain the
source does not already give. If a rendering is ever wanted, it belongs beside
this manifest and inside its digests.
"""
from __future__ import annotations

import hashlib
import json
import pathlib
import re
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
MANIFEST = ROOT / "docs" / "release" / "specification-manifest.json"

# The artifacts a baseline publishes. The specification is normative; everything
# below it is derived from it and named as such.
ARTIFACTS = {
    "specification": "docs/APR_SPECIFICATION.md",
    "schema": "schemas/apr-1.0-beta.6.schema.json",
    "schemaBase": "schemas/apr-1.0.schema.json",
    "typeRegistry": "schemas/apr-types-1.0.json",
    "coverageRegistry": "tests/registry.json",
    "shapeManifest": "tests/spec-shape/manifest.json",
    "reviewRubric": "tests/spec-semantic/rubric.json",
    "derivedExamples": "tests/Conformance/beta6/spec-examples.json",
}

CORPUS = ROOT / "tests" / "Conformance" / "beta6"


def digest(path: pathlib.Path) -> str:
    return "sha256:" + hashlib.sha256(path.read_bytes()).hexdigest()


def corpus_digest() -> tuple[str, int]:
    """One digest over every corpus file, so a fixture edit moves the baseline."""
    files = sorted(
        p for p in CORPUS.rglob("*")
        if p.is_file() and p.name != "spec-examples.json"
    )
    accumulator = hashlib.sha256()
    for path in files:
        accumulator.update(str(path.relative_to(ROOT)).encode("utf-8"))
        accumulator.update(path.read_bytes())
    return "sha256:" + accumulator.hexdigest(), len(files)


def spec_facts(text: str) -> dict[str, object]:
    def field(name: str) -> str | None:
        match = re.search(rf"\*\*{re.escape(name)}:\*\* `?([^`\n]+)`?", text)
        return match.group(1).strip() if match else None

    return {
        "documentVersion": field("Specification document version"),
        "formatVersion": field("Describes format version"),
        "status": field("Status"),
        "published": field("Published"),
        "normativeClauses": len(re.findall(
            r"\*\*(MUST NOT|MUST|SHALL NOT|SHALL|REQUIRED|SHOULD NOT|SHOULD|MAY)\*\*", text)),
        "ruleIdentifiers": len(set(re.findall(r"\[(APR-[A-Z]+-\d{3})\]", text))),
        "anchors": len(set(re.findall(r"\{#([a-z0-9-]+)\}", text))),
        "executableExamples": len(re.findall(r"^```apr-example$", text, re.MULTILINE)),
    }


def build() -> dict:
    spec = (ROOT / ARTIFACTS["specification"]).read_text(encoding="utf-8")
    corpus, corpus_files = corpus_digest()
    return {
        "$comment": (
            "GENERATED by scripts/build-spec.py. Identifies the exact artifact set a "
            "baseline publishes. The specification is normative; every other artifact "
            "is derived from it."
        ),
        "manifestVersion": "apr-specification-manifest-1",
        "specification": spec_facts(spec),
        "artifacts": {
            name: {"path": path, "sha256": digest(ROOT / path)}
            for name, path in ARTIFACTS.items()
        },
        "corpus": {
            "path": "tests/Conformance/beta6",
            "files": corpus_files,
            "sha256": corpus,
        },
    }


def main() -> int:
    generated = json.dumps(build(), indent=2) + "\n"

    if "--write" in sys.argv:
        MANIFEST.parent.mkdir(parents=True, exist_ok=True)
        MANIFEST.write_text(generated, encoding="utf-8")
        print(f"Wrote {MANIFEST.relative_to(ROOT)}")
        return 0

    if not MANIFEST.exists():
        print(f"{MANIFEST.relative_to(ROOT)} does not exist; run with --write")
        return 1

    if MANIFEST.read_text(encoding="utf-8") != generated:
        print(f"{MANIFEST.relative_to(ROOT)} does not describe the current artifacts.")
        print("A published baseline must identify the bytes it published.")
        print("Run scripts/build-spec.py --write")
        return 1

    facts = build()["specification"]
    print(f"Specification manifest is current: {facts['formatVersion']}, "
          f"{facts['ruleIdentifiers']} rules, {facts['executableExamples']} examples.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
