#!/usr/bin/env python3
"""Assemble the renderer conformance suite a renderer driver answers.

The document suite asks what an implementation did with a document. Twelve rules
cannot be asked that way, because no file is valid or invalid because of how a
renderer behaves. This suite asks the other question — what did a person end up in
front of — and `docs/RENDERER_CONFORMANCE.md` defines the answer's shape.

Every case document is validated as it is assembled. A renderer case resting on a
document the format rejects would test a renderer against something no reader
should have shown it in the first place.

    python3 scripts/build-renderer-suite.py
    python3 scripts/build-renderer-suite.py --write
"""
from __future__ import annotations

import hashlib
import importlib.util
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
CASES = ROOT / "tests" / "Conformance" / "beta6" / "renderer" / "cases.json"
SUITE = ROOT / "tests" / "Conformance" / "beta6" / "renderer-suite.json"
SPEC = ROOT / "docs" / "APR_SPECIFICATION.md"
CONTRACT = ROOT / "docs" / "RENDERER_CONFORMANCE.md"
SUITE_VERSION = "apr-beta6-renderer-conformance-1"

sys.path.insert(0, str(ROOT / "scripts"))
_spec = importlib.util.spec_from_file_location("validate_apr", ROOT / "scripts" / "validate-apr.py")
validate_apr = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(validate_apr)


def build() -> dict:
    source = json.loads(CASES.read_text(encoding="utf-8"))
    members = validate_apr.spec_members()
    cases, problems = [], []

    for case in source["cases"]:
        report = validate_apr.Report(case["id"])
        validate_apr.validate_form(report, case["document"], members)
        invalid = [f"{f['code']} at {f['path']}"
                   for f in report.findings if f["severity"] == "error"]
        if invalid:
            problems.append(f"{case['id']}: {'; '.join(invalid)}")
            continue
        cases.append({
            "id": f"renderer:{case['id']}",
            "rules": case["rules"],
            "asks": case["asks"],
            # Which surface answers. Avalonia does not export, so the rule about what
            # an export must not do belongs to the exporter's driver.
            "surface": case.get("surface", "renderer"),
            "document": json.dumps(case["document"], indent=2, ensure_ascii=False) + "\n",
        })

    return {
        "$comment": ("GENERATED by scripts/build-renderer-suite.py. Do not edit. A "
                     "renderer driver reads this one file and needs nothing else; the "
                     "shape of its answer is docs/RENDERER_CONFORMANCE.md."),
        "suiteVersion": SUITE_VERSION,
        "formatVersion": "1.0-beta.6",
        "specificationSha256": "sha256:" + hashlib.sha256(SPEC.read_bytes()).hexdigest(),
        "contractSha256": "sha256:" + hashlib.sha256(CONTRACT.read_bytes()).hexdigest(),
        "cases": cases,
    }, problems


def main() -> int:
    suite, problems = build()
    if problems:
        print(f"{len(problems)} case document(s) the format rejects:")
        for problem in problems:
            print(f"  - {problem}")
        print("\nA renderer case rests on a document a reader should have accepted. "
              "Fix the case,\nnot the validator.")
        return 1

    text = json.dumps(suite, indent=2, ensure_ascii=False) + "\n"
    rules = sorted({rule for case in suite["cases"] for rule in case["rules"]})
    if "--write" in sys.argv:
        SUITE.write_text(text, encoding="utf-8")
        print(f"Wrote {SUITE.relative_to(ROOT)}: {len(suite['cases'])} cases naming "
              f"{len(rules)} rules")
        return 0
    if not SUITE.exists() or SUITE.read_text(encoding="utf-8") != text:
        print(f"{SUITE.relative_to(ROOT)} is stale; run "
              f"scripts/build-renderer-suite.py --write")
        return 1
    print(f"Renderer suite is current: {len(suite['cases'])} cases naming {len(rules)} rules")
    return 0


if __name__ == "__main__":
    sys.exit(main())
