#!/usr/bin/env python3
"""Cross-reference the GUI element inventory against what the GUI tests exercise.

tests/gui-inventory.json lists every interactive element found by walking the rendered
visual tree. This asks the next question: which of them does a test actually touch?

An element counts as covered when its accessible name or content appears in the GUI test
sources - which is how those tests find controls, by name. The match is textual and so
approximate at the edges, but it is exhaustive in the direction that matters: a control
nothing mentions is certainly untested.

    python3 scripts/check-gui-coverage.py [--json]

Writes generated evidence under TestResults/gui-evidence (or
PROMPTRESPONSE_GUI_EVIDENCE_DIR) and prints a summary.
"""
import json
import os
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
EVIDENCE = pathlib.Path(os.environ.get(
    "PROMPTRESPONSE_GUI_EVIDENCE_DIR", ROOT / "TestResults" / "gui-evidence"))
INVENTORY = EVIDENCE / "gui-inventory.json"
EXERCISED = EVIDENCE / "gui-exercised.json"
GUI_TESTS = ROOT / "tests" / "PromptResponse.Desktop.Tests" / "Gui"
OUT = EVIDENCE / "gui-coverage.json"

# Control-template parts, not app-authored controls. A ComboBox's dropdown button is
# Avalonia's, not ours, and is unreachable by keyboard by design.
TEMPLATE_PART_KINDS = {"RepeatButton"}


def test_corpus():
    return "\n".join(p.read_text(encoding="utf-8", errors="ignore")
                     for p in GUI_TESTS.rglob("*.cs"))


def main():
    if not INVENTORY.is_file():
        sys.exit("Run GuiInventoryTests first to generate gui-inventory.json in the evidence directory")

    inventory = json.loads(INVENTORY.read_text(encoding="utf-8"))
    corpus = test_corpus()

    # Elements the exhaustive driver actually activated at runtime. This is stronger
    # evidence than a name appearing in test source, where it might sit in a comment.
    activated = set()
    if EXERCISED.is_file():
        for row in json.loads(EXERCISED.read_text(encoding="utf-8")):
            activated.add((row["surface"], row["label"]))

    rows, covered, untested = [], 0, []
    for surface, data in inventory["surfaces"].items():
        for element in data["elements"]:
            label = element.get("Name") or element.get("Text")
            kind = element["Kind"]
            if kind in TEMPLATE_PART_KINDS or not label:
                continue
            # A control is exercised if a test mentions the string it is found by.
            by_name = label in corpus
            by_activation = (surface, label) in activated
            hit = by_name or by_activation
            rows.append({"surface": surface, "kind": kind, "label": label, "covered": hit,
                         "how": "activated" if by_activation else ("named-in-test" if by_name else "none")})
            if hit:
                covered += 1
            else:
                untested.append({"surface": surface, "kind": kind, "label": label})

    total = len(rows)
    payload = {
        "comment": "Which interactive elements the GUI tests exercise, matched by the name "
                   "tests use to find them. Regenerated by scripts/check-gui-coverage.py.",
        "totals": {"addressable": total, "covered": covered, "untested": len(untested),
                   "percent": round(100 * covered / total, 1) if total else 0.0},
        "untested": sorted(untested, key=lambda r: (r["surface"], r["kind"], r["label"])),
        "elements": rows,
    }
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")

    if "--json" in sys.argv:
        print(json.dumps(payload["totals"], indent=2))
        return 0

    print(f"Addressable elements: {total}")
    print(f"  covered   {covered:3}  ({payload['totals']['percent']}%)")
    print(f"  untested  {len(untested):3}")
    if untested:
        print("\nUntested, by surface:")
        current = None
        for row in payload["untested"]:
            if row["surface"] != current:
                current = row["surface"]
                print(f"\n  {current}")
            print(f"    {row['kind']:<20} {row['label']}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
