#!/usr/bin/env python3
"""Cross-reference the GUI element inventory against what the GUI tests exercise.

`GuiInventoryTests` writes every interactive element it finds by walking the rendered
visual tree; `ExhaustiveInteractionTests` writes every element it actually activated at
runtime. This asks the next question: which of them does a test touch, and how?

Two answers, and only one of them is a gate.

**Activated** means the exhaustive driver clicked, typed into or toggled the control.
That is evidence, and `--gate` holds it to the floor in tests/gui-activation-floor.json,
which ratchets the way tests/Conformance/beta6/rule-evidence.json does.

**Named in a test** means the control's accessible name appears somewhere in the GUI test
sources — which is how those tests find controls, so it is suggestive. It is also
satisfied by a mention in a comment, so it is reported and never gated. A control neither
activated nor named is certainly untested, and that direction is exhaustive.

    python3 scripts/check-gui-coverage.py [--json] [--gate]

Reads and writes generated evidence under TestResults/gui-evidence (or
PROMPTRESPONSE_GUI_EVIDENCE_DIR), which the Desktop test suite produces. Run that first.
"""
import json
import os
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
EVIDENCE = pathlib.Path(os.environ.get(
    "PROMPTRESPONSE_GUI_EVIDENCE_DIR", ROOT / "TestResults" / "gui-evidence"))
INVENTORY = EVIDENCE / "gui-inventory.json"
EXERCISED = EVIDENCE / "gui-exercised.json"
GUI_TESTS = ROOT / "tests" / "PromptResponse.Desktop.Tests" / "Gui"
OUT = EVIDENCE / "gui-coverage.json"
FLOOR = ROOT / "tests" / "gui-activation-floor.json"

# Control-template parts, not app-authored controls. A ComboBox's dropdown button is
# Avalonia's, not ours, and is unreachable by keyboard by design.
TEMPLATE_PART_KINDS = {"RepeatButton"}


def test_corpus():
    return "\n".join(p.read_text(encoding="utf-8", errors="ignore")
                     for p in GUI_TESTS.rglob("*.cs"))


def main():
    if not INVENTORY.is_file():
        sys.exit("Run GuiInventoryTests first to generate gui-inventory.json in the evidence directory")

    inventory = json.loads(INVENTORY.read_text(encoding="utf-8"))
    corpus = test_corpus()

    # Elements the exhaustive driver actually activated at runtime. This is stronger
    # evidence than a name appearing in test source, where it might sit in a comment.
    activated = set()
    if EXERCISED.is_file():
        for row in json.loads(EXERCISED.read_text(encoding="utf-8")):
            activated.add((row["surface"], row["label"]))

    rows, covered, untested = [], 0, []
    for surface, data in inventory["surfaces"].items():
        for element in data["elements"]:
            label = element.get("Name") or element.get("Text")
            kind = element["Kind"]
            if kind in TEMPLATE_PART_KINDS or not label:
                continue
            # A control is exercised if a test mentions the string it is found by.
            by_name = label in corpus
            by_activation = (surface, label) in activated
            hit = by_name or by_activation
            rows.append({"surface": surface, "kind": kind, "label": label, "covered": hit,
                         "how": "activated" if by_activation else ("named-in-test" if by_name else "none")})
            if hit:
                covered += 1
            else:
                untested.append({"surface": surface, "kind": kind, "label": label})

    total = len(rows)
    activated_count = sum(1 for row in rows if row["how"] == "activated")
    payload = {
        "comment": "Which interactive elements the GUI tests exercise, matched by the name "
                   "tests use to find them. Regenerated by scripts/check-gui-coverage.py.",
        "totals": {"addressable": total, "covered": covered, "untested": len(untested),
                   "activated": activated_count,
                   "activatedPercent": round(100 * activated_count / total, 1) if total else 0.0,
                   "percent": round(100 * covered / total, 1) if total else 0.0},
        "untested": sorted(untested, key=lambda r: (r["surface"], r["kind"], r["label"])),
        "elements": rows,
    }
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")

    if "--json" in sys.argv:
        print(json.dumps(payload["totals"], indent=2))
        return 0

    print(f"Addressable elements: {total}")
    print(f"  activated {activated_count:3}  ({payload['totals']['activatedPercent']}%)  "
          f"— the gate")
    print(f"  covered   {covered:3}  ({payload['totals']['percent']}%)  "
          f"— including {covered - activated_count} named in a test and not activated")
    print(f"  untested  {len(untested):3}")
    if "--gate" in sys.argv:
        floor = json.loads(FLOOR.read_text(encoding="utf-8"))
        if activated_count < floor["activated"]:
            print(f"\nGUI activation fell to {activated_count} from a floor of "
                  f"{floor['activated']}. A control that stopped being exercised is a "
                  f"control nothing is holding, whatever the textual figure says.")
            return 1
        if activated_count > floor["activated"]:
            print(f"\nActivation rose to {activated_count} from {floor['activated']}: "
                  f"raise the floor in {FLOOR.relative_to(ROOT)}.")
    if untested:
        print("\nUntested, by surface:")
        current = None
        for row in payload["untested"]:
            if row["surface"] != current:
                current = row["surface"]
                print(f"\n  {current}")
            print(f"    {row['kind']:<20} {row['label']}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
