#!/usr/bin/env python3
"""Run an opt-in, local-only MLX review of the APR specification.

This tool emits review leads for a human. It is deliberately not a conformance
test and is not part of the fast CI path.
"""

from __future__ import annotations

import argparse
import hashlib
import importlib.metadata
import json
import sys
from datetime import UTC, datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "python"))

from promptresponse.spec_semantic import (  # noqa: E402
    SemanticReviewError,
    build_prompt,
    load_rubric,
    parse_model_report,
)


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--model-path",
        type=Path,
        required="--dry-run" not in sys.argv,
        help="Existing local MLX model directory. Network model downloads are not allowed.",
    )
    # Pinned so two runs are comparable. Override for a different reviewer.
    parser.add_argument(
        "--model-id",
        default="Qwen/Qwen3-8B",
        help="Pinned source model identifier.",
    )
    parser.add_argument(
        "--model-revision",
        default="b968826d9c46dd6066d109eabc6255188de91218-mlx-q4",
        help="Pinned model revision, including any local quantisation.",
    )
    parser.add_argument("--seed", type=int, default=0)
    parser.add_argument(
        "--chunk",
        type=int,
        default=6,
        help="Rubric items per prompt. A rubric that carries its own excerpts is "
             "asked in bounded batches; one prompt holding 135 items and the whole "
             "specification answers none of them well.",
    )
    parser.add_argument(
        "--budget",
        type=int,
        default=12000,
        help="Characters of excerpt per prompt. A batch is closed when either this "
             "or --chunk is reached, so one large section cannot make a prompt the "
             "model answers in prose.",
    )
    parser.add_argument("--max-tokens", type=int, default=4096)
    parser.add_argument("--spec", type=Path, default=ROOT / "docs" / "APR_SPECIFICATION.md")
    parser.add_argument(
        "--rubric",
        type=Path,
        default=ROOT / "tests" / "spec-semantic" / "completeness-rubric.json",
        help="Rubric to ask. The default is the completeness rubric, one item per "
             "ungated rule, regenerated by scripts/build-review-rubric.py.",
    )
    parser.add_argument(
        "--output", type=Path, default=ROOT / "artifacts" / "spec-semantic-review.json"
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Report what would be asked — batches, items, prompt sizes — and load "
             "no model. Verifies the plumbing on a machine with no MLX.",
    )
    return parser.parse_args()


def batches_of(args) -> tuple[str, list, dict, bool, list]:
    payload = json.loads(args.rubric.read_text(encoding="utf-8"))
    version, items = load_rubric(payload)
    excerpts = {i["id"]: i.get("excerpt") for i in payload["items"]}
    scoped = all(excerpts.get(item.id) for item in items)
    return version, items, excerpts, scoped, pack(items, excerpts, args) if scoped else [items]


def pack(items: list, excerpts: dict, args) -> list[list]:
    """Group items into prompts bounded by payload, not only by count.

    Sections differ in size by an order of magnitude, so a fixed item count
    produces batches that differ by the same. One batch of six carrying 46,000
    characters is what made the model return prose where JSON was asked for,
    while its neighbours at 4,000 answered cleanly.
    """
    groups, current, size = [], [], 0
    for item in items:
        cost = len(excerpts[item.id] or "")
        if current and (len(current) >= args.chunk or size + cost > args.budget):
            groups.append(current)
            current, size = [], 0
        current.append(item)
        size += cost
    if current:
        groups.append(current)
    return groups


def dry_run(args) -> int:
    """Say what would be asked, without a model."""
    version, items, excerpts, scoped, groups = batches_of(args)
    sizes = [sum(len(excerpts[i.id] or "") for i in g) for g in groups]
    print(f"rubric {version}: {len(items)} items")
    print(f"  excerpt-scoped: {scoped}"
          + ("" if scoped else "  (whole specification sent per prompt)"))
    print(f"  batches: {len(groups)} of at most {args.chunk} items")
    if sizes:
        print(f"  prompt payload: largest {max(sizes)} characters, "
              f"median {sorted(sizes)[len(sizes) // 2]}")
    return 0


def main() -> int:
    args = arguments()
    if args.dry_run:
        return dry_run(args)
    if not args.model_path.is_dir():
        raise SystemExit(f"--model-path must be an existing local directory: {args.model_path}")
    for path in (args.spec, args.rubric):
        if not path.is_file():
            raise SystemExit(f"required input does not exist: {path}")

    try:
        from mlx_lm import generate, load
        from mlx_lm.sample_utils import make_sampler
        import mlx.core as mx
    except ImportError as exc:
        raise SystemExit(
            "MLX support is not installed. On Apple silicon run: "
            "uv sync --directory python --extra semantic-review"
        ) from exc

    # A rubric item may carry the passage it is about. When every item does, the
    # reviewer sees that passage and nothing else, which is the whole point: a
    # question about one rule answered against three thousand lines is a question
    # about whether the model can find the rule.
    rubric_version, items, excerpts, scoped, batches = batches_of(args)
    specification = args.spec.read_text(encoding="utf-8")

    mx.random.seed(args.seed)
    model, tokenizer = load(str(args.model_path))

    def present(text: str) -> str:
        """Shape a prompt the way the model was trained to receive it.

        A reasoning model asked for JSON through a raw completion prompt answers
        with its chain of thought first; enable_thinking=False turns that off
        where the template supports it, and the parser strips it where it does
        not.
        """
        if not getattr(tokenizer, "chat_template", None):
            return text
        message = [{"role": "user", "content": text}]
        try:
            return tokenizer.apply_chat_template(
                message, tokenize=False, add_generation_prompt=True, enable_thinking=False)
        except TypeError:
            return tokenizer.apply_chat_template(
                message, tokenize=False, add_generation_prompt=True)

    # Greedy decoding, expressed the way current mlx-lm expects it. The older
    # "temp=0.0" keyword was removed upstream, and passing it raised a TypeError
    # before any review could run.
    findings = []
    for number, batch in enumerate(batches, start=1):
        text = ("\n\n".join(f"### {item.id}\n\n{excerpts[item.id]}" for item in batch)
                if scoped else specification)
        prompt = present(build_prompt(
            specification=text, rubric_version=rubric_version, items=batch))
        raw_report = generate(
            model,
            tokenizer,
            prompt=prompt,
            max_tokens=args.max_tokens,
            sampler=make_sampler(temp=0.0),
            verbose=False,
        )
        try:
            part = parse_model_report(raw_report, rubric_version=rubric_version, items=batch)
        except SemanticReviewError as exc:
            # One batch the model answered badly is one batch, not the run. A
            # reviewer that discards twenty-two good batches because the
            # twenty-third came back malformed has cost more than it found, and
            # the failure is silent: the artifact keeps whatever it held before.
            findings.extend({"id": item.id, "status": "no_model_answer",
                             "evidence": [], "reason": f"batch {number} rejected: {exc}"}
                            for item in batch)
            print(f"  batch {number}/{len(batches)}: rejected ({exc})", file=sys.stderr)
        else:
            findings.extend(part["findings"])
            print(f"  batch {number}/{len(batches)}: {len(part['findings'])} findings",
                  file=sys.stderr)
        # Checkpoint. A local run costs an hour, and a crash at batch twenty
        # should not cost the nineteen that answered.
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(json.dumps(
            {"kind": "non-authoritative-apr-specification-semantic-review",
             "warning": "Partial: this run has not finished.",
             "report": {"rubric_version": rubric_version, "findings": findings}},
            indent=2) + "\n", encoding="utf-8")
    report = {"rubric_version": rubric_version, "findings": findings}
    output = {
        "kind": "non-authoritative-apr-specification-semantic-review",
        "warning": "This is local-model review evidence, not an APR conformance result.",
        "created_at": datetime.now(UTC).isoformat(),
        "model": {
            "path": str(args.model_path.resolve()),
            "id": args.model_id,
            "revision": args.model_revision,
            "mlx_lm_version": importlib.metadata.version("mlx-lm"),
            "seed": args.seed,
            "temperature": 0.0,
            "max_tokens": args.max_tokens,
        },
        "inputs": {
            "specification": str(args.spec.resolve()),
            "specification_sha256": sha256(args.spec),
            "rubric": str(args.rubric.resolve()),
            "rubric_sha256": sha256(args.rubric),
            "rubric_items": len(items),
            "batches": len(batches),
            "scoped_excerpts": scoped,
        },
        "report": report,
    }
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(output, indent=2) + "\n", encoding="utf-8")
    print(f"Wrote non-authoritative review evidence to {args.output}")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except SemanticReviewError as exc:
        raise SystemExit(f"Rejected model report: {exc}") from exc
